### ISSUE TITLE
Error:  getInternalNameOfClass(), node version 14.13.0

### ISSUE THREAD

**Issue by amit-dhakad** [bootsoon/ng-circle-progress#131]
Error: getInternalNameOfClass() called on a non-ES5 class: expected CircleProgressComponent to have an inner class declaration

**Comment by bootsoon** [comment]
Could you post your code?

**Comment by dlaugh14** [comment]
Having. the same issue here with node 12.19.0.

`Warning: Invalid constructor parameter decorator in /Users/{user}/WebstormProjects/{project}/node_modules/ng-circle-progress/fesm2015/ng-circle-progress.js:
() => [
{ type: CircleProgressOptions },
{ type: ElementRef },
{ type: undefined, decorators: [{ type: Inject, args: [DOCUMENT,] }] }
]
Error: Error on worker #7: Error: getInternalNameOfClass() called on a non-ES5 class: expected CircleProgressComponent to have an inner class declaration
at Esm5ReflectionHost.getInternalNameOfClass (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
at DelegatingReflectionHost.getInternalNameOfClass (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
at Object.extractDirectiveMetadata (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/directive.js:237:69)
at ComponentDecoratorHandler.analyze (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/component.js:143:47)
at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
at analyze (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
at _loop_1 (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
at NgccTraitCompiler.TraitCompiler.analyzeClass (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
at NgccTraitCompiler.analyzeFile (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
at DecorationAnalyzer.analyzeProgram (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
at ClusterMaster.onWorkerMessage (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:194:27)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:54:95
at ClusterMaster.<anonymous> (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:292:57)
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.next (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at /Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:115:75
at new Promise (<anonymous>)
at Object.__awaiter (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:111:16)
at EventEmitter.<anonymous> (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:286:32)
at EventEmitter.emit (events.js:314:20)
Error: NGCC failed.
at NgccProcessor.process (/Users/{user}/WebstormProjects/{project}/node_modules/@ngtools/webpack/src/ngcc_processor.js:76:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:579:31
at SyncHook.eval (eval at create (/Users/{user}/WebstormProjects/{project}/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
at SyncHook.lazyCompileHook (/Users/{user}/WebstormProjects/{project}/node_modules/tapable/lib/Hook.js:154:20)
at webpack (/Users/{user}/WebstormProjects/{project}/node_modules/webpack/lib/webpack.js:55:30)
at init (/Users/{user}/WebstormProjects/{project}/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/karma.js:130:20)
at Array.invoke (/Users/{user}/WebstormProjects/{project}/node_modules/di/lib/injector.js:75:15)
at Injector.get (/Users/{user}/WebstormProjects/{project}/node_modules/di/lib/injector.js:48:43)
at /Users/{user}/WebstormProjects/{project}/node_modules/karma/lib/server.js:153:61
at Array.forEach (<anonymous>)
at Server._start (/Users/{user}/WebstormProjects/{project}/node_modules/karma/lib/server.js:153:23)
at Injector.invoke (/Users/{user}/WebstormProjects/{project}/node_modules/di/lib/injector.js:75:15)
at Server.start (/Users/{user}/WebstormProjects/{project}/node_modules/karma/lib/server.js:127:22)
27 10 2020 16:10:07.094:ERROR [karma-server]: Server start failed on port 9876: Error: NGCC failed.

{user}-MacBook-Pro {project} % (node:95188) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95187) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95187) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95186) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95186) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95186) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95191) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95190) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95190) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95190) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:95189) UnhandledPromiseRejectionWarning: Error: write EPIPE
at process.target._send (internal/child_process.js:806:20)
at process.target.send (internal/child_process.js:677:19)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:50:21
at new Promise (<anonymous>)
at Object.exports.sendMessageToMaster (/Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/utils.js:45:16)
at /Users/{user}/WebstormProjects/{project}/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:103:66
at step (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:141:27)
at Object.throw (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:122:57)
at rejected (/Users/{user}/WebstormProjects/{project}/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:95189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:95189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

package.json - 
`"dependencies": {
"@angular/animations": "9.1.12",
"@angular/common": "9.1.12",
"@angular/compiler": "9.1.12",
"@angular/core": "9.1.12",
"@angular/forms": "9.1.12",
"@angular/localize": "9.1.12",
"@angular/platform-browser": "9.1.12",
"@angular/platform-browser-dynamic": "9.1.12",
"@angular/router": "9.1.12",
"@ng-bootstrap/ng-bootstrap": "6.2.0",
"@ngx-translate/core": "12.0.0",
"@ngx-translate/http-loader": "^6.0.0",
"@optimizely/optimizely-sdk": "^3.4.1",
"@types/crypto-js": "^3.1.43",
"atatus-js": "^3.1.1",
"bootstrap": "4.4.1",
"core-js": "2.6.3",
"crypto-js": "^3.3.0",
"dateformat": "^3.0.3",
"jexl": "^2.2.2",
"js-yaml": "3.13.1",
"lodash": "4.17.20",
"ng-circle-progress": "^1.6.0",
"ng5-slider": "1.2.4",
"ngx-favicon": "^1.1.0",
"ngx-konami": "^1.7.1",
"ngx-perfect-scrollbar": "9.0.0",
"rxjs": "6.6.3",
"tslib": "^1.10.0",
"url-polyfill": "^1.0.13",
"z-schema": "^4.2.2",
"zone.js": "~0.10.2"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.901.12",
"@angular/cli": "9.1.12",
"@angular/compiler-cli": "^9.1.12",
"@angular/language-service": "^9.1.12",
"@biesbjerg/ngx-translate-extract": "^2.3.4",
"@ngx-rocket/scripts": "^3.0.0",
"@types/jasmine": "^3.3.8",
"@types/jasminewd2": "^2.0.3",
"@types/lodash": "^4.14.108",
"@types/node": "^12.11.1",
"codelyzer": "^5.1.2",
"gulp": "4.0.2",
"gulp-hash": "4.2.2",
"hads": "^1.7.2",
"handlebars": "4.5.0",
"htmlhint": "^0.11.0",
"https-proxy-agent": "^2.1.0",
"jasmine-core": "~3.4.0",
"jasmine-spec-reporter": "^4.2.1",
"karma": "~4.1.0",
"karma-chrome-launcher": "^3.1.0",
"karma-cli": "~2.0.0",
"karma-coverage-istanbul-reporter": "2.1.1",
"karma-jasmine": "^2.0.1",
"karma-junit-reporter": "^1.2.0",
"karma-spec-reporter": "^0.0.32",
"ngentest": "^0.4.1",
"protractor": "~5.4.0",
"puppeteer": "2.1.1",
"stylelint": "~10.0.1",
"stylelint-config-recommended-scss": "~3.3.0",
"stylelint-config-standard": "~18.3.0",
"stylelint-scss": "~3.9.0",
"ts-node": "^8.3.0",
"tslint": "~5.18.0",
"typescript": "~3.8.3"
}
`

For another library that had this error I had to just downgrade the version because the one I was using was for Angular 10. This version is Angular 9, just as I have.

It was https://github.com/zefoy/ngx-perfect-scrollbar/releases/tag/v9.0.0

- [ ]

**Comment by hazembenhassine** [comment]
> Could you post your code?

I encountered the same problem. This requires no code, just installing the dependency using npm and attempting to serve the angular app causes this issue for me.

**Comment by MoroccanGeek** [comment]
> 
> 
> > Could you post your code?
> 
> I encountered the same problem. This requires no code, just installing the dependency using npm and attempting to serve the angular app causes this issue for me.

Yes the same here
