### ISSUE TITLE
XHR error (404 Not Found) 

### ISSUE THREAD

**Issue by SwapnilDube** [bootsoon/ng-circle-progress#45]
Hi Team, 
I am facing below issue. My application is in angular 4, in VS2017. I have added package as suggested of version 1.0.0.

Error: XHR error (404 Not Found) loading http://localhost:18520/ng-circle-progress
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:18520/node_modules/zone.js/dist/zone.js:1056:39)
	    at ZoneDelegate.invokeTask (http://localhost:18520/node_modules/zone.js/dist/zone.js:424:31)
	    at Zone.runTask (http://localhost:18520/node_modules/zone.js/dist/zone.js:191:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:18520/node_modules/zone.js/dist/zone.js:486:38)

Kindly suggest.
Thanks

**Comment by bootsoon** [comment]
No idea. ng-circle-progress does not use XHR.
