### ISSUE TITLE
Unexpected token import error with SSR

### ISSUE THREAD

**Issue by arun-maddheshia** [bootsoon/ng-circle-progress#60]
I'm trying to make `ng-circle-progress` work with Universal but getting this error when trying to run:

 ```
play@0.0.1 compile:server /Users/play
 tsc -p server.tsconfig.json
 play@0.0.1 serve:ssr /Users/play
 node dist/server
/Users/play/node_modules/ng-circle-progress/index.js:1
(function (exports, require, module, __filename, __dirname) { import { Component, EventEmitter, Input, NgModule, Output } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.ng-circle-progress (/Users/play/server/main.js:13946:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! play@0.0.1 serve:ssr: `node dist/server`
npm ERR! Exit status 1
```

**Comment by virtuoushub** [comment]
I am also running into this issue when attempting to unit test a component using `ng-circle-progress
` with Jest. Happy to open a separate issue if that is a better tracking mechanism, although I suspect if a fix / answer to this issue is provided than my issue will also be resolved.
