### ISSUE TITLE
 problem to render

### ISSUE THREAD

**Issue by romiZeppe** [bootsoon/ng-circle-progress#78]
Hello, I am using the package and when I want to render the site, this error appears.

(function (exports, require, module, __filename, __dirname) { import { Component, EventEmitter, Input, NgModule, Output } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

I do not know how to solve it or if there is something wrong. The version I'm using is Angular 6

If you could help me I would appreciate it very much

**Comment by bootsoon** [comment]
No idea. Could you post come code?
